from django.conf.urls.defaults import *

urlpatterns = patterns('',
    (r'^/?$', 'populous.advertising.views.index'),
    (r'^classifieds/?$', 'populous.advertising.views.classifieds_index'),
    (r'^classifieds/list/?$', 'django.views.generic.simple.direct_to_template', {'template': 'advertising/classifieds/list.html'}),
#    (r'^classifieds/categories/?$', 'populous.advertising.views.classifieds_category_list'),
#    (r'^classifieds/categories/(?P<slug>[\w-]+)/?$', 'populous.advertising.views.classifieds_category_detail'),
#    (r'^classifieds/order/activate/$', 'populous.advertising.views.activate_form'),
#    (r'^classifieds/order/preform/$', 'django.views.generic.simple.direct_to_template', {'template': 'advertising/classifieds/order_preform'}),
#    (r'^classifieds/subcategories/?$', 'populous.advertising.views.classifieds_subcategory_list'),
#    (r'^classifieds/subcategories/(?P<slug>[\w-]+)/?$', 'populous.advertising.views.classifieds_subcategory_detail'),
#    (r'^classifieds/(?P<slug>[\w-]+)/?$', 'populous.advertising.views.classifieds_detail'),
#    (r'^classifieds/(?P<slug>[\w-]+)/map/?$', 'populous.advertising.views.classifieds_map'),
#    (r'^coupons/businesses/(?P<slug>[\w-]+)/?$', 'populous.advertising.views.coupons_business'),
#    (r'^coupons/businesses/(?P<slug>[\w-]+)/map/?$', 'populous.advertising.views.coupons_map'),
#    (r'^coupons/?$', 'populous.advertising.views.coupons_list'),
#    (r'^coupons/(?P<slug>[\w-]+)/?$', 'populous.advertising.views.coupons_detail'),
#    (r'^coupons/(?P<slug>[\w-]+)/map/?$', 'populous.advertising.views.coupons_map'),
#    (r'^coupons/(?P<slug>[\w-]+)/print/?$', 'populous.advertising.views.coupons_print'),
#    (r'^graphicads/?$', 'populous.advertising.views.graphicads_list'),
#    (r'^graphicads/(?P<slug>[\w-]+)/?$', 'populous.advertising.views.graphicads_detail'),
#    (r'^textads/?$', 'populous.advertising.views.textads_list'),
#    (r'^textads/(?P<slug>[\w-]+)/?$', 'populous.advertising.views.textads_detail'),
#    (r'^textads/(?P<slug>[\w-]+)/map/?$', 'populous.advertising.views.textads_map'),
)